name: blogAPI CI/CD

on:
  push:
    branches:
      - "main"
      - "master"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Push repo
        uses: actions/checkout@v3
<<<<<<< HEAD
      - name: Print hello
        run: echo "hello world"
=======
      - name: Install Python
        uses: actions/setup-python@v3
        with:
          python-version: "3.9"
      - name: Upgrade Pip
        run: python -m pip install --upgrade pip
      - name: Install all dependencies
        run: pip install -r requirements.txt
  
  heroku-deployment:
    runs-on: ubuntu-latest
    needs: [build]
    
    environment:
      name: heroku_production

    steps:
      - name: Get actions
        uses: actions/checkout@v3
      - name: Deploying to heroku
        uses: akhileshns/heroku-deploy@v3.14.15 # This is the action
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: ${{secrets.APP_NAME}}#"YOUR APP's NAME" #Must be unique in Heroku
          heroku_email: ${{secrets.MY_EMAIL}}#"YOUR EMAIL"
>>>>>>> 4f329d8d3bbc83a8401e86f264dfac340f246e4d
