# Example for installing and starting simple Node.js application
---
- name: Install and start Node.js application
  hosts: web
  become: true

  vars:
    node_apps_location: /usr/local/opt/node

  tasks:
    - name: Update repos.
      ansible.builtin.dnf:
        update_cache: true

    - name: Install EPEL repo.
      ansible.builtin.yum_repository:
        name: epel-release
        description: EPEL repo
        baseurl:
          - https://dl.fedoraproject.org/pub/epel/epel-release-latest-7.noarch.rpm
        state: present

    - name: Import Remi GPG key.
      ansible.builtin.rpm_key:
        key: https://rpms.remirepo.net/RPM-GPG-KEY-remi
        state: present

    - name: Install Remi repo.
      ansible.builtin.yum_repository:
        name: remi-repo
        description: Remi repo
        baseurl:
          - https://rpms.remirepo.net/enterprise/remi-release-7.rpm
        state: present

#    - name: Ensure firewalld is stopped (since this is for testing)
#      ansible.builtin.service:
#        name: firewalld
#        state: stopped
#
    - name: Install Node.js.
      ansible.builtin.dnf:
        name: npm
        state: present
        enablerepo: epel

    - name: Install forever (to run Node.js app).
      community.general.npm:
        name: forever
        global: true
        state: present

    - name: Ensure Node.js app directory exists.
      ansible.builtin.file:
        path: "{{ node_apps_location }}"
        state: directory
        mode: '0755'
    
    - name: Copy example Node.js app to server.
      ansible.builtin.copy:
        src: app
        dest: "{{ node_apps_location }}"
        mode: '0755'

    - name: Install Node.js app dependencies.
      community.general.npm:
        path: "{{ node_apps_location }}/app"
        state: present

    - name: Check list of running Node.js apps.
      ansible.builtin.command:
        cmd: forever list
      register: forever_list
      changed_when: false

    - name: Start Node.js app.
      ansible.builtin.command:
        cmd: "forever start {{ node_apps_location }}/app/app.js"
      when: "forever_list.stdout.find(node_apps_location + '/app/app.js') == -1"
