# Example for installing and starting simple Node.js application
---
- name: Install and start Node.js application
  hosts: all
  become: true

  vars:
    node_apps_location: /usr/local/opt/node

  tasks:
    - name: Install EPEL repo.
      ansible.builtin.apt:
        name: epel-release
        state: present

    - name: Import Remi GPG key.
      ansible.builtin.rpm_key:
        key: https://rpms.remirepo.net/RPM-GPG-KEY-remi
        state: present

    - name: Install Remi repo.
      ansible.builtin.apt:
        name: https://rpms.remirepo.net/enterprise/remi-release-7.rpm
        state: present

    - name: Ensure firewalld is stopped (since this is for testing)
      ansible.builtin.service:
        name: firewalld
        state: stopped

    - name: Install Node.js.
      ansible.builtin.apt:
        name: npm
        state: present

    - name: Install forever (to run Node.js app).
      community.general.npm:
        name: forever
        global: true
        state: present
