services:
  nginx:
    build: .
    ports:
      - "80:80"
      - "443:443"
      - "8081:8081"
      - "8082:8082"
    volumes: 
      - ./default.conf.template:/etc/nginx/conf.d/default.conf.template
      - ./nginx-selfsigned.crt:/etc/nginx/ssl/nginx-selfsigned.crt
      - ./nginx-selfsigned.key:/etc/nginx/ssl/nginx-selfsigned.key
      - ./nginx/logs:/var/log/nginx
    